command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "4b9b953939869799"
  - name: GENIE_SPACE_ID
    value: ""
  - name: DATABRICKS_CATALOG
    value: "akash_s"
  - name: DATABRICKS_SCHEMA
    value: "finance_and_accounting"
  - name: PGHOST
    value: "ep-mute-dew-d1b8fz0c.database.us-west-2.cloud.databricks.com"
  - name: PGUSER
    value: "aba1ec33-e4db-47b2-9c51-60eef4a6603f"
  - name: PGDATABASE
    value: "postgres"
  - name: PGPORT
    value: "5432"
  - name: PGSSLMODE
    value: "require"
  - name: LAKEBASE_INSTANCE_NAME
    value: "finance-ops-db"
  - name: SMTP_HOST
    value: "smtp.gmail.com"
  - name: SMTP_PORT
    value: "587"
  - name: SMTP_USER
    value: ""
  - name: SMTP_PASSWORD
    value: ""
  - name: SMTP_FROM
    value: ""
  - name: ESCALATION_RECIPIENT
    value: ""
resources:
  - name: sql-warehouse
    sql_warehouse:
      id: "4b9b953939869799"
      permission: CAN_USE
  - name: claude-endpoint
    serving_endpoint:
      name: "databricks-claude-sonnet-4-5"
      permission: CAN_QUERY
  - name: mas-supervisor
    serving_endpoint:
      name: "mas-3744e932-endpoint"
      permission: CAN_QUERY
  - name: finance-ops-db
    database_instance:
      name: "finance-ops-db"
      permission: CAN_USE
